### ISSUE TITLE
Best name ever

### ISSUE THREAD

**Issue by drudge** [heyshadowsmith/deep-diff-pizza#1]
Thank you for creating the module! I'm using it in my new [n8n.io](https://n8n.io) node for determining differences between two inputs: https://github.com/drudge/n8n-nodes-changes

I just wanted to say that this is definitely the best module name I've seen on the internet.

**Comment by heyshadowsmith** [comment]
@drudge That rules! I'm stoked it fit your use case and that you love the name so much. 🍕

I **had** to go the extra mile and brand it like a pizzeria. It would be such a shame if I didn't.

And naturally, I'm now working on shirts because why not. 🤷🏻‍♂️
