### ISSUE TITLE
Remove value not detected when the value is empty string, array, undefined or null

### ISSUE THREAD

**Issue by linhanhui** [heyshadowsmith/deep-diff-pizza#2]
hi not sure if this is a fixable issue, so I am aware that when the object value contains `[]`, `{}`, `undefined` or `null` the `deepDiff` returns empty array `[]` e.g. 

```
const objA = {
  prop1: [],
  prop2: 'hello'
};

const objB =  {
 prop2: 'hello'
};

deepDiff(objA, objB)
```

**Comment by heyshadowsmith** [comment]
🤔 I feel there's a simple solution to accommodate this.

Is this a blocker for something you're working on, or did you happen to discover this playing with the package?

**Comment by heyshadowsmith** [comment]
**Update:** I'm away from my computer for a few days, so I tinkered with this on my phone.

I have reproduced this and zeroed in on what the fix could look like.

I'll drop a patch soon. 👍

**Comment by linhanhui** [comment]
> **Update:** I'm away from my computer for a few days, so I tinkered with this on my phone.
> 
> I have reproduced this and zeroed in on what the fix could look like.
> 
> I'll drop a patch soon. 👍

thanks smith!

**Comment by FionaWee** [comment]
Hi Smith! I'm facing the same issue as well, it's a blocker for me on my side...
